channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - lxml
  - python=3.8
  - matplotlib
  - numpy
  - pandas
  - networkx
  - scikit-learn
  - watermark
  # pip
  - pip
  - pip:
    - scikit-network
